matrix:
  include:

    - language: python
      python:
          - "3.6"

      sudo: false
      cache:
          directories:
              - "~/selftest"

      install:
          - cp ~/README.md ~/fhem
          - cd ~/fhem && pip install -e .
          
      script:
          - cd ~/selftest && python selftest.py

    - language: python
      python:
          - "2.7"

      sudo: false
      cache:
          directories:
              - "~/selftest"

      install:
          - cp ~/README.md ~/fhem
          - cd ~/fhem && pip install -e .

      script:
          - cd ~/selftest && python selftest.py

