matrix:
  include:

    - language: python
      python:
          - "3.6"

      sudo: false
      cache:
          directories:
              - "~/selftest"

      install:
          - pwd
          - python setup.py install
          
      script:
          - cd ~/selftest && python selftest.py

    - language: python
      python:
          - "2.7"

      sudo: false
      cache:
          directories:
              - "~/selftest"

      install:
          - cp ~/domschl/python-fhem/README.md ~/domschl/python-fhem/fhem
          - cd ~/domschl/python-fhem/fhem && pip install -e .

      script:
          - cd ~/selftest && python selftest.py

