matrix:
  include:

    - language: python
      python:
          - "3.6"

      cache:
          directories:
              - "~/selftest"

      install:
          - sudo apt-get install -y libio-socket-ssl-perl
          - cd fhem
          - cp ../README.md .
          - python setup.py install
          - cd ..
          
      script:
          - cd selftest && python selftest.py

    - language: python
      python:
          - "2.7"

      cache:
          directories:
              - "~/selftest"

      install:
          - sudo apt-get install -y libio-socket-ssl-perl
          - cd fhem
          - cp ../README.md .
          - python setup.py install
          - cd ..

      script:
          - cd selftest && python selftest.py

