matrix:
  include:

    - language: python
      python:
          - "3.6"

      sudo: false
      cache:
          directories:
              - "~/selftest"

      install:
          - cd fhem && pip install -e . && cd ..
          
      script:
          - cd selftest && python selftest.py

    - language: python
      python:
          - "2.7"

      sudo: false
      cache:
          directories:
              - "~/selftest"

      install:
          - cd fhem && pip install -e . && cd ..

      script:
          - cd selftest && python selftest.py

